frontend:
    @echo installing frontend
catalogue:
    @echo installing catalogue
cart:
    @echo installing cart
payment:
    @echo installing payment
mysql:
    @echo installing mysql
mongodb:
    @echo installing mongodb
rabbitmq:
    @echo installing rabbitmq
redis:
    @echo installing redis
user:
    @echo installing user
shipping:
    @echo installing shipping

