help:  ##  print this message
    @fgrep -h "##" $(MAKEFILE-LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:  ##  Install frontend component
    @echo Installing frontend
catalogue:  ##  Install catalogue component
    @echo Installing catalogue
cart:  ##  Install cart component
    @echo Installing cart
payment:  ##  Install payment component
    @echo Installing payment
mysql:  ##  Install mysql component
    @echo Installing mysql
mongodb:  ##  Install mongodb component
    @echo Installing mongodb
rabbitmq:  ##  Install rabbitmq component
    @echo Installing rabbitmq
redis:  ##  Install catalogue component
    @echo Installing redis
user:  ##  Install user component
    @echo Installing user
shipping:  ##  Install shipping component
    @echo installing shipping

